# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Anton Telesh
email: telesh91@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://antontelesh.github.io" # the base hostname & protocol for your site
twitter_username: AntonTelesh
github_username:  Antontelesh

# Build settings
markdown: kramdown
gems:
  - octopress-autoprefixer
  - github-pages